import re

with open('G:/Github Repos/Tasbee7/quran-V3.html', encoding='utf-8') as f:
    content = f.read()

old_start = '  function _tpRenderAyahs() {'
old_end = "    document.body.style.overflow = '';\n  }"

s = content.find(old_start)
e = content.find(old_end, s) + len(old_end)
print(f'Block: {s} -> {e} ({e-s} chars)')

new_block = (
    "  function _tpRenderAyahs() {\n"
    "    const container = document.getElementById('tpContent');\n"
    "    container.innerHTML = '';\n"
    "    let lastSurah = null;\n"
    "    _tp.ayahs.forEach((a, i) => {\n"
    "      if (a.surah !== lastSurah) {\n"
    "        const div = document.createElement('div');\n"
    "        div.className = 'tp-surah-name';\n"
    "        div.textContent = a.surahName;\n"
    "        container.appendChild(div);\n"
    "        lastSurah = a.surah;\n"
    "      }\n"
    "      const span = document.createElement('span');\n"
    "      span.className = 'tp-ayah';\n"
    "      span.id = 'tp-a-' + i;\n"
    "      span.dataset.idx = i;\n"
    "      const textSpan = document.createElement('span');\n"
    "      textSpan.className = 'tp-ayah-text';\n"
    "      a.text.split(' ').forEach(w => {\n"
    "        const ws = document.createElement('span');\n"
    "        ws.className = 'tp-word';\n"
    "        ws.textContent = w + ' ';\n"
    "        textSpan.appendChild(ws);\n"
    "      });\n"
    "      const markerSpan = document.createElement('span');\n"
    "      markerSpan.className = 'tp-ayah-marker';\n"
    "      markerSpan.textContent = ' ﴾' + _tpArabicNum(a.ayah) + '﴿ ';\n"
    "      markerSpan.onclick = (e) => { e.stopPropagation(); _tpSelectAyah(i); };\n"
    "      span.appendChild(textSpan);\n"
    "      span.appendChild(markerSpan);\n"
    "      container.appendChild(span);\n"
    "    });\n"
    "  }\n"
    "\n"
    "  function _tpSelectAyah(idx) {\n"
    "    document.querySelectorAll('.tp-ayah.selected-target').forEach(el => el.classList.remove('selected-target'));\n"
    "    _tp.expectedIdx = idx;\n"
    "    const el = document.getElementById('tp-a-' + idx);\n"
    "    if (el) { el.classList.add('selected-target', 'current-expected'); el.scrollIntoView({ behavior: 'smooth', block: 'center' }); }\n"
    "    showCustomToast('اختيرت: ' + _tp.ayahs[idx].surahName + ' — الآية ' + _tp.ayahs[idx].ayah);\n"
    "  }\n"
    "\n"
    "  function _tpSetExpected(idx) {\n"
    "    document.querySelectorAll('.tp-ayah.current-expected, .tp-ayah.selected-target')\n"
    "      .forEach(el => el.classList.remove('current-expected', 'selected-target'));\n"
    "    _tp.expectedIdx = idx;\n"
    "    if (idx !== null && idx < _tp.ayahs.length) {\n"
    "      const el = document.getElementById('tp-a-' + idx);\n"
    "      if (el) { el.classList.add('current-expected'); el.scrollIntoView({ behavior: 'smooth', block: 'center' }); }\n"
    "    }\n"
    "  }\n"
    "\n"
    "  let _tpAudioCtx = null;\n"
    "  let _tpScriptProc = null;\n"
    "  let _tpAllSamples = [];\n"
    "  let _tpStreamTimer = null;\n"
    "\n"
    "  async function tpToggleRecord() {\n"
    "    if (!_tarteelReady) return;\n"
    "    if (_tp.recording) {\n"
    "      _tp.recording = false;\n"
    "      clearInterval(_tp.timerInterval);\n"
    "      clearInterval(_tpStreamTimer);\n"
    "      document.getElementById('tpLiveStrip').classList.remove('active');\n"
    "      if (_tp.stream) { _tp.stream.getTracks().forEach(t => t.stop()); _tp.stream = null; }\n"
    "      if (_tpScriptProc) { _tpScriptProc.disconnect(); _tpScriptProc = null; }\n"
    "      if (_tpAudioCtx) { _tpAudioCtx.close().catch(()=>{}); _tpAudioCtx = null; }\n"
    "      if (_tpAllSamples.length > 0) {\n"
    "        const total = _tpAllSamples.reduce((s,c) => s + c.length, 0);\n"
    "        const merged = new Float32Array(total);\n"
    "        let pos = 0;\n"
    "        _tpAllSamples.forEach(c => { merged.set(c, pos); pos += c.length; });\n"
    "        _tpAllSamples = [];\n"
    "        _tarteelTasmeeMode = true;\n"
    "        document.getElementById('tpMicBtn').className = 'tp-mic-btn processing';\n"
    "        document.getElementById('tpMicIcon').style.display = '';\n"
    "        document.getElementById('tpStopIcon').style.display = 'none';\n"
    "        document.getElementById('tpRecDot').className = 'tp-rec-dot';\n"
    "        _tarteelWorker.postMessage({ type: 'recognize', audio: merged }, [merged.buffer]);\n"
    "      } else {\n"
    "        document.getElementById('tpMicBtn').className = 'tp-mic-btn';\n"
    "        document.getElementById('tpMicIcon').style.display = '';\n"
    "        document.getElementById('tpStopIcon').style.display = 'none';\n"
    "        document.getElementById('tpRecDot').className = 'tp-rec-dot';\n"
    "        document.getElementById('tpRecTimer').textContent = '00:00';\n"
    "      }\n"
    "    } else {\n"
    "      try {\n"
    "        _tp.stream = await navigator.mediaDevices.getUserMedia({ audio: true });\n"
    "        _tpAudioCtx = new AudioContext({ sampleRate: 16000 });\n"
    "        const src = _tpAudioCtx.createMediaStreamSource(_tp.stream);\n"
    "        _tpScriptProc = _tpAudioCtx.createScriptProcessor(4096, 1, 1);\n"
    "        _tpAllSamples = [];\n"
    "        _tpScriptProc.onaudioprocess = ev => {\n"
    "          if (!_tp.recording) return;\n"
    "          _tpAllSamples.push(new Float32Array(ev.inputBuffer.getChannelData(0)));\n"
    "        };\n"
    "        src.connect(_tpScriptProc);\n"
    "        _tpScriptProc.connect(_tpAudioCtx.destination);\n"
    "        _tp.recording = true;\n"
    "        _tp.timerStart = Date.now();\n"
    "        _tp.timerInterval = setInterval(() => {\n"
    "          const s = Math.floor((Date.now() - _tp.timerStart) / 1000);\n"
    "          document.getElementById('tpRecTimer').textContent =\n"
    "            String(Math.floor(s/60)).padStart(2,'0') + ':' + String(s%60).padStart(2,'0');\n"
    "        }, 1000);\n"
    "        _tpStreamTimer = setInterval(() => {\n"
    "          if (!_tp.recording || _tpAllSamples.length === 0) return;\n"
    "          const total = _tpAllSamples.reduce((s,c) => s+c.length, 0);\n"
    "          if (total < 16000 * 1.2) return;\n"
    "          const merged = new Float32Array(total);\n"
    "          let pos = 0;\n"
    "          _tpAllSamples.forEach(c => { merged.set(c, pos); pos += c.length; });\n"
    "          _tarteelWorker.postMessage({ type: 'stream', audio: merged.slice() });\n"
    "        }, 1800);\n"
    "        document.getElementById('tpLiveStrip').classList.add('active');\n"
    "        document.getElementById('tpLiveStrip').innerHTML =\n"
    "          '<span class=\"tp-live-word\" style=\"opacity:0.6;animation:none\">جاري الاستماع...</span>';\n"
    "        document.getElementById('tpMicBtn').className = 'tp-mic-btn recording';\n"
    "        document.getElementById('tpMicIcon').style.display = 'none';\n"
    "        document.getElementById('tpStopIcon').style.display = '';\n"
    "        document.getElementById('tpRecDot').className = 'tp-rec-dot recording';\n"
    "      } catch (err) { _tpShowError(err.message); }\n"
    "    }\n"
    "  }\n"
    "\n"
    "  function _tpHandleStreamResult(data) {\n"
    "    if (!data.transcript) return;\n"
    "    const strip = document.getElementById('tpLiveStrip');\n"
    "    strip.innerHTML = '';\n"
    "    data.transcript.split(' ').forEach((w, i) => {\n"
    "      const sp = document.createElement('span');\n"
    "      sp.className = 'tp-live-word';\n"
    "      sp.textContent = w;\n"
    "      sp.style.animationDelay = (i * 0.04) + 's';\n"
    "      strip.appendChild(sp);\n"
    "    });\n"
    "    if (data.match && data.match.score > 0.55) {\n"
    "      const idx = _tp.ayahs.findIndex(a => a.surah === data.match.surah && a.ayah === data.match.ayah);\n"
    "      if (idx >= 0 && !_tp.revealed.has(idx)) {\n"
    "        document.querySelectorAll('.tp-ayah.current-expected').forEach(el => el.classList.remove('current-expected'));\n"
    "        const el = document.getElementById('tp-a-' + idx);\n"
    "        if (el) el.classList.add('current-expected');\n"
    "      }\n"
    "    }\n"
    "  }\n"
    "\n"
    "  function _aiHandleResult(result) {\n"
    "    _tarteelProcessing = false;\n"
    "    document.getElementById('tpMicBtn').className = 'tp-mic-btn';\n"
    "    document.getElementById('tpRecTimer').textContent = '00:00';\n"
    "    document.getElementById('tpLiveStrip').classList.remove('active');\n"
    "    if (!result || !result.surah) {\n"
    "      showCustomToast('لم يُتعرَّف على الآية — حاول مجدداً');\n"
    "      _tp.errors++; _tpUpdateErrors(); return;\n"
    "    }\n"
    "    const matchIdx = _tp.ayahs.findIndex(a => a.surah === result.surah && a.ayah === result.ayah);\n"
    "    if (matchIdx < 0) {\n"
    "      showCustomToast((result.surahName || 'سورة') + ' — الآية ' + result.ayah + ' (ليست في هذه الصفحة)');\n"
    "      _tp.errors++; _tpUpdateErrors(); return;\n"
    "    }\n"
    "    const el = document.getElementById('tp-a-' + matchIdx);\n"
    "    const isCorrect = _tp.expectedIdx === null || matchIdx === _tp.expectedIdx;\n"
    "    _tp.revealed.add(matchIdx);\n"
    "    el.classList.remove('current-expected', 'selected-target');\n"
    "    el.classList.add('revealed', isCorrect ? 'correct' : 'error', isCorrect ? 'tp-flash-correct' : 'tp-flash-error');\n"
    "    setTimeout(() => el.classList.remove('tp-flash-correct', 'tp-flash-error'), 1200);\n"
    "    if (!isCorrect) { _tp.errors++; _tpUpdateErrors(); }\n"
    "    const words = el.querySelectorAll('.tp-word');\n"
    "    words.forEach((w, i) => {\n"
    "      w.style.opacity = '0';\n"
    "      w.style.animation = 'tp-word-in 0.2s ease ' + (i * 0.06) + 's forwards';\n"
    "    });\n"
    "    const a = _tp.ayahs[matchIdx];\n"
    "    showCustomToast((isCorrect ? '✓ ' : '✗ ') + a.surahName + ' — الآية ' + a.ayah);\n"
    "    _tpSetExpected(matchIdx + 1 < _tp.ayahs.length ? matchIdx + 1 : null);\n"
    "    el.scrollIntoView({ behavior: 'smooth', block: 'center' });\n"
    "  }\n"
    "\n"
    "  function _aiSetProcessing() { _tarteelProcessing = true; document.getElementById('tpMicBtn').className = 'tp-mic-btn processing'; }\n"
    "\n"
    "  function _tpShowError(msg) {\n"
    "    _tarteelProcessing = false; _tp.recording = false;\n"
    "    clearInterval(_tp.timerInterval); clearInterval(_tpStreamTimer);\n"
    "    if (_tp.stream) { _tp.stream.getTracks().forEach(t => t.stop()); _tp.stream = null; }\n"
    "    if (_tpScriptProc) { _tpScriptProc.disconnect(); _tpScriptProc = null; }\n"
    "    if (_tpAudioCtx) { _tpAudioCtx.close().catch(()=>{}); _tpAudioCtx = null; }\n"
    "    document.getElementById('tpMicBtn').className = 'tp-mic-btn';\n"
    "    document.getElementById('tpMicIcon').style.display = '';\n"
    "    document.getElementById('tpStopIcon').style.display = 'none';\n"
    "    document.getElementById('tpRecDot').className = 'tp-rec-dot';\n"
    "    document.getElementById('tpRecTimer').textContent = '00:00';\n"
    "    document.getElementById('tpLiveStrip').classList.remove('active');\n"
    "    showCustomToast(msg || 'خطأ في التسجيل');\n"
    "  }\n"
    "\n"
    "  function _tpUpdateErrors() { document.getElementById('tpErrorBadge').textContent = _tpArabicNum(_tp.errors) + ' أخطاء'; }\n"
    "  function tpPrev() { const c = _tp.expectedIdx !== null ? _tp.expectedIdx : _tp.ayahs.length; _tpSetExpected(Math.max(0, c-1)); }\n"
    "  function tpSkipBack() { const c = _tp.expectedIdx !== null ? _tp.expectedIdx : _tp.ayahs.length; _tpSetExpected(Math.max(0, c-3)); }\n"
    "  function tpToggleText() {\n"
    "    _tp.showText = !_tp.showText;\n"
    "    document.getElementById('tpEyeBtn').classList.toggle('active', _tp.showText);\n"
    "    document.querySelectorAll('.tp-ayah:not(.revealed) .tp-ayah-text').forEach(el => el.classList.toggle('show', _tp.showText));\n"
    "  }\n"
    "\n"
    "  function closeTasmeePro() {\n"
    "    _tarteelTasmeeMode = false; _tp.recording = false;\n"
    "    clearInterval(_tp.timerInterval); clearInterval(_tpStreamTimer);\n"
    "    if (_tp.stream) { _tp.stream.getTracks().forEach(t => t.stop()); _tp.stream = null; }\n"
    "    if (_tpScriptProc) { _tpScriptProc.disconnect(); _tpScriptProc = null; }\n"
    "    if (_tpAudioCtx) { _tpAudioCtx.close().catch(()=>{}); _tpAudioCtx = null; }\n"
    "    _tpAllSamples = [];\n"
    "    document.getElementById('tpLiveStrip').classList.remove('active');\n"
    "    document.getElementById('tasmeeProPanel').style.display = 'none';\n"
    "    document.body.style.overflow = '';\n"
    "  }"
)

new_content = content[:s] + new_block + content[e:]
with open('G:/Github Repos/Tasbee7/quran-V3.html', 'w', encoding='utf-8') as f:
    f.write(new_content)
print('Done. Size:', len(new_content))
